name: 'Convert to HTML and PDF'
on: push
permissions:
  contents: read
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Convert HTML
        uses: docker://pandoc/core:latest
        with:
          args: >-
            resume.md
            -d defaults.yml
            -o resume.html
      - name: Convert PDF
        uses: docker://pandoc/core:latest
        with:
          args: >-
            resume.md
            -d defaults.yml
            -t html
            -o resume.pdf
      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: resume.*
